# Variáveis
@hostname = http://localhost:8080
@api = {{hostname}}/investments

### Criar um novo ativo (Ação)
POST {{api}}
Content-Type: application/json

{
  "type": "ACAO",
  "symbol": "BBAS3",
  "quantity": 100,
  "purchasePrice": 19.68,
  "purchaseDate": "2025-07-31"
}

### Criar um novo ativo (Cripto)
POST {{api}}
Content-Type: application/json

{
  "type": "CRIPTO",
  "symbol": "BTC",
  "quantity": 1,
  "purchasePrice": 150000.00,
  "purchaseDate": "2025-08-15"
}

### Listar todos os ativos
GET {{api}}

### Listar ativos por tipo (CRIPTO)
GET {{api}}?type=CRIPTO

### Buscar ativo por ID
# Altere o ID para um que exista no seu banco
GET {{api}}/1

### Atualizar um ativo
# Altere o ID para um que exista no seu banco
PUT {{api}}/1
Content-Type: application/json

{
  "quantity": 150,
  "purchasePrice": 20.50
}


### Remover um ativo
# Altere o ID para um que exista no seu banco
DELETE {{api}}/2


### Obter resumo da carteira
GET {{api}}/summary

